### ISSUE TITLE
Twitter account

### ISSUE THREAD

**Issue by mthenw** [apex/apex.run#16]
Not exactly "web" issue bit I didn't know where to put that. We could post updated about releases, retweet (@tj's) articles, etc. :D

Thoughts?

Propositions:
- apex_run
- apexrun
- apex_serverless

**Comment by tj** [comment]
sgtm! not sure which name haha

**Comment by johannesboyne** [comment]
`apex_run` == `http://apex.run/` ;-)

**Comment by mthenw** [comment]
yup :)

**Comment by mthenw** [comment]
https://twitter.com/apexserverless

**Comment by RickWong** [comment]
The account is not working anymore. Link on website therefore broken.

**Comment by tj** [comment]
ah I removed it, too much work maintaining multiple twitter accounts. I'll update

**Comment by kaihendry** [comment]
https://twitter.com/apexserverless is still linked and not working btw
