### ISSUE TITLE
Boilerplate link is broken

### ISSUE THREAD

**Issue by clintonhalpin** [apex/apex.run#19]
Getting 404 on "Boilerplate example with Terraform"

https://github.com/apex/boilerplate

![screen shot 2016-03-07 at 9 00 13 am](https://cloud.githubusercontent.com/assets/523933/13571455/1bf40bd0-e443-11e5-8c3b-5a94e0f4c405.png)

**Comment by mthenw** [comment]
Thanks for reporting.

**Comment by clintonhalpin** [comment]
That was quick! NP!
